version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - run: git reset --hard
      - run: git pull
      - node/with-cache:
          steps:
            - add_ssh_keys:
                fingerprints:
                  - "53:e9:1a:71:cf:11:fd:ac:21:d2:b9:fb:dd:33:0d:b9"
            - run:
                name: deploy
                command: |
                  scp -r -o StrictHostKeyChecking=no dist/* root@198.211.112.212:/var/www/mtlearnandgrow
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
